# Generated by Django 5.2.7 on 2025-10-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdnauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchamodels',
            name='captcha_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='captchamodels',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='captchamodels',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
