# Generated by Django 5.2.7 on 2025-10-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['pub_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='blogtopiccategory',
            options={'verbose_name': '话题分类', 'verbose_name_plural': '话题分类'},
        ),
        migrations.AlterField(
            model_name='blogtopiccategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
