# Generated by Django 5.2.7 on 2025-10-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_category_blog_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category_id',
            new_name='category',
        ),
    ]
